import React from "react";
import { Sparkles, Hotel, ImageIcon, Share2, Wallet, Users } from "lucide-react";

const FEATURES = [
  {
    icon: Sparkles,
    title: "AI-Powered Itineraries",
    desc: "Day-by-day plans generated by AI, tailored to your destination, duration, and travel style.",
    accent: "from-cyan-500 to-blue-600",
  },
  {
    icon: Hotel,
    title: "Curated Hotel Picks",
    desc: "Hotel recommendations matched to your budget, complete with ratings and addresses.",
    accent: "from-emerald-500 to-teal-600",
  },
  {
    icon: ImageIcon,
    title: "Real Destination Photos",
    desc: "Every place and stay comes with real, live-fetched photos — no generic stock art.",
    accent: "from-purple-500 to-indigo-600",
  },
  {
    icon: Wallet,
    title: "Budget-Aware Planning",
    desc: "From backpacker to luxury, your plan adapts to the budget range you choose.",
    accent: "from-amber-500 to-orange-600",
  },
  {
    icon: Users,
    title: "Built for Any Crew",
    desc: "Solo, couple, family, or a large group — itineraries adjust to who's traveling.",
    accent: "from-pink-500 to-rose-600",
  },
  {
    icon: Share2,
    title: "Shareable Trip Links",
    desc: "Save your itinerary and share it instantly with travel companions in one click.",
    accent: "from-sky-500 to-cyan-600",
  },
];

const Features = () => {
  return (
    <section className="w-full bg-white py-20 px-6 md:px-16">
      <div className="max-w-6xl mx-auto">
        <div className="text-center max-w-2xl mx-auto mb-14">
          <span className="text-cyan-600 font-semibold text-sm uppercase tracking-wide">
            Why WonderMate
          </span>
          <h2 className="text-3xl md:text-4xl font-extrabold text-gray-900 mt-2">
            Everything you need to plan the perfect trip
          </h2>
          <p className="text-gray-500 mt-4 text-lg">
            One prompt, one full itinerary — hotels, activities, and photos included.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
          {FEATURES.map((feature, index) => (
            <div
              key={index}
              className="group p-7 rounded-2xl border border-gray-100 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300"
            >
              <div
                className={`h-12 w-12 rounded-xl bg-gradient-to-r ${feature.accent} text-white flex items-center justify-center mb-5 group-hover:scale-110 transition-transform duration-300`}
              >
                <feature.icon size={22} />
              </div>
              <h3 className="text-lg font-bold text-gray-900 mb-2">{feature.title}</h3>
              <p className="text-gray-500 text-sm leading-relaxed">{feature.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;
